name: Govern-Console CI/CD
on:
  push:
    # paths:
    #   - 'packages/govern-console/**'
    branches:
      - 'test-branch'
      - 'develop'
      - 'master'

env:
  working-directory: packages/govern-console

jobs:
  install-and-build-depedencies:
    runs-on: ubuntu-latest
    container: fleek/create-react-app:node-15
    name: builds and deploys console
    defaults:
      run:
        working-directory: ${{env.working-directory}}
    steps:
      - uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.5
      
    - name: activate rinkeby's fleek
      run: mv fleek/console.staging.json .fleek.json

    - name: deploy app on rinkeby's fleek
      id: deploy1
      uses: fleekhq/action-deploy@v0.1.4-beta2
      with:
        apiKey: ${{ secrets.FLEEK_API_KEY }}
        workDir: ${{env.working-directory}}
